# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - make clean
    - go generate ./...
    # You may remove this if you don't use go modules.
    #- go mod download
    # you may remove this if you don't need go generate
    #- golangci-lint run ./...
    #- touch filename.txt
project_name: cluster-ssh-tail
builds:
- main: cmd/main.go
  env:
  - CGO_ENABLED=0
#id: cluster-ssh-tail
#id: "{{ .ProjectName }}-{{ .Version }}"
  ldflags:
  - -s -w -X main.Version={{ .Version }} -X main.GitCommit={{ .Commit }} -X main.Author={{ .Env.AUTHOR }}

  #- -s -w -X main.Version="miversion" -X main.GitCommit={{ .Commit }} -X main.author="David Rios"
  #- -s -w -X main.versionNumber={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.author={{ .Env.Author }} -X main.copyright={{ .Env.CopyRight }}
# Set up GO111MODULE variable
#- GO111MODULE=on
#hooks:
#	pre:
#   - cmd: first-script.sh
#     dir: "{{ dir .Dist }}"
#     env:
#     - HOOK_SPECIFIC_VAR={{ .Env.GLOBAL_VAR  }}
#     - second-script.sh


archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
